info:
  description: Thomas' config sample
  url: https://git01.ops.medplus.com/hcp/scratch-config-repo

greeting:
  title: This is the default REPO title
  message: And this is the  default REPO message

owner: Thomas

---
spring:
  profiles: prof1
  
greeting:
  title: This is the prof1 REPO title
  message: And this is the prof1 REPO message

owner: Thomas Profile 1

---
spring:
  profiles: prof2
  
greeting:
  title: This is the prof2 REPO title
  message: And this is the prof2 REPO message

owner: Thomas Profile 2

