info:
  description: Thomas' config sample
  url: https://git01.ops.medplus.com/hcp/scratch-config-repo

greeting:
  title: This is the default REPO title
  message: And this is the  default REPO message

---
spring:
  profiles: prof1
  
greeting:
  title: This is the VERSION1 prof1 REPO title
  message: And this is the VERSION1 prof1 REPO message

---
spring:
  profiles: prof2
  
greeting:
  title: This is the VERSION1 prof2 REPO title
  message: And this is the VERSION1 prof2 REPO message

